name: 'OpenFaaS Actions'
description: 'Setup Github Actions with faas-cli'
author: 'Kumar Utsav Anand'
branding:
  icon: 'play'
  color: 'gray-dark'
inputs:
  faas-cli-version:
    description: 'Version of faas-cli container image'
    default: 'latest-root'
    required: false
  cli-args:
    description: 'Arguments passed to faas-cli'
    default: 'faas-cli version'
    required: false
runs:
  using: 'docker'
  image: 'docker://utsavanand2/faas-cli:latest-root'
  args:
      - "${{ inputs.cli-args }}"